project:
  type: website
  output-dir: docs

website:
  title: "paul_romans"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    toc: true
    toc-location: left
    theme: superhero
    fontsize: 1.2em
    linestretch: 1.8
    css: styles.css

listing:
  contents: 
    - posts/proto_paul/1the*.qmd
    - posts/proto_paul/gal*.qmd
    - posts/proto_paul/phm*.qmd
    - posts/proto_paul/1co*.qmd
    - posts/proto_paul/2co*.qmd
    - posts/proto_paul/rom*.qmd
    - posts/proto_paul/phil*.qmd

  sort:
    - "date"
    - "title"

editor: visual
