project:
  type: website
  output-dir: docs

website:
  title: "NT_letters"
  sidebar:
    style: "docked"
    search: true
    contents: posts
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-navigation: true
  
format:
  html:
    toc: true
    toc-location: left
    theme: superhero
    fontsize: 1.2em
    linestretch: 1.8
    css: styles.css

listing:
  contents: 
    - posts/proto_paul/1the*.qmd
    - posts/proto_paul/gal*.qmd
    - posts/proto_paul/phm*.qmd
    - posts/proto_paul/1co*.qmd
    - posts/proto_paul/2co*.qmd
    - posts/proto_paul/rom*.qmd
    - posts/proto_paul/phil*.qmd
    - posts/deutero_paul/2the*.qmd
    - posts/deutero_paul/col*.qmd
    - posts/deutero_paul/eph*.qmd
    - posts/trito_paul/1tim*.qmd
    - posts/trito_paul/2tim*.qmd
    - posts/trito_paul/tit*.qmd
    - posts/john_nco/jas*.qmd
    - posts/john_nco/1pet*.qmd
    - posts/john_nco/2pet*.qmd
    - posts/john_nco/jud*.qmd
    - posts/john_nco/heb*.qmd
    - posts/john_nco/1joh*.qmd
    - posts/john_nco/2joh*.qmd
    - posts/john_nco/3joh*.qmd
  sort: "false"

editor: visual
